Docker 3
Otus-DevOps-2018-09/dnvlasov_microservices pull request #5
Opened 2018-12-22 19:05 UTC by dnvlasov

# Выполнено ДЗ № 14

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано: 
- Пункт 1  Создана  новая структура приложения состоящая из трех сервисов 
- Пункт 2  post-py  - сервис отвечающий за написание постов
- Пункт 3 comment - сервис отвечающий за написание комментариев
- Пункт 4 ui - веб-интерфейс, работающий с другими сервисами
- Пункт 5 Создана специальная сеть для контейнеров reddit 
- Пункт 6 Запуск приложения
- Пункт 7 ui - улучшаем образ
- Пункт 8 Создание Docker volume подключение его к контейнеру MongoDB
- Пункт 9 Перезапуск приложения с volume

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-12-24 18:50 UTC, enkov submitted a review, later dismissed
Добрый день!
А почему у вас не настроена интеграция с travis?

2018-12-24 18:53 UTC, enkov requested changes
Нужно настроить интеграцию с travis.

2018-12-24 19:49 UTC, dnvlasov commented
Добавил.

2018-12-25 01:22 UTC, enkov commented
Нет не настроили. Посмотрите внимательно как должны запускаться тесты.
`curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash`

2018-12-25 08:38 UTC, dnvlasov commented
> 
<sub>[View in Slack](https://devops-team-otus.slack.com/archives/CDARU75RS/p1545726456001300)</sub>

2018-12-25 08:40 UTC, dnvlasov commented
https://travis-ci.com/Otus-DevOps-2018-09/dnvlasov_microservices
Тесты запускаются.

2018-12-25 08:43 UTC, enkov commented
Не запускаются! У вас команда запуска выглядит вот так
 `- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh`,
а должно быть вот так
`curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash`.
То что у вас сейчас это просто скачивание файла и конечно же оно завершается успешно.

2018-12-25 09:44 UTC, dnvlasov commented
Ок. Да косячёк был и тянется он из   infra от туда копировал, никто не заметил.
Поравил. Спасибо.

2018-12-25 09:59 UTC, enkov approved these changes

2018-12-25 09:59 UTC, enkov commented
Воот! Теперь порядок.

2018-12-25 10:03 UTC, merged